spring:
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/mmall?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: mmall
    password: 123456
    tomcat:
      max-active: 50
    dbcp2:
      max-idle: 20
      min-idle: 10
  session:
    store-type: none

mybatis:
  mapper-locations: classpath:/mappers/*.xml

logging.level.org.springframework.boot.autoconfigure: ERROR
